[package]
name = "cash-test-harness"
description = "Runs the YAML compatibility cases against cash"
version.workspace = true
authors.workspace = true
categories.workspace = true
edition.workspace = true
keywords.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
publish = false

[lib]
bench = false

[lints]
workspace = true

[features]
default = []
# Enable insta snapshot support
insta = ["dep:insta"]

[dependencies]
anyhow = { workspace = true }
assert_cmd = { workspace = true }
assert_fs = { workspace = true }
clap = { workspace = true, features = ["derive", "env"] }
colored = "3.1.1"
diff = { workspace = true }
glob = { workspace = true }
insta = { workspace = true, features = ["yaml"], optional = true }
junit-report = "0.9.0"
os-release = "0.1.0"
regex = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_yaml = { workspace = true }
strip-ansi-escapes = "0.2.1"
tokio = { workspace = true, features = ["rt", "rt-multi-thread", "sync"] }
