# bash-completion compatibility shims — cash, D40.
#
# Tools generate a bash completion script and expect you to source it:
#
#     docker completion bash > ~/.docker-completion.bash
#     kubectl completion bash
#     gh completion -s bash
#
# The ones generated by clap (rustup, cargo, ripgrep, and most Rust CLIs) are
# self-contained and work in cash as-is. The ones generated by Cobra — which is
# to say most of the Go ecosystem: docker, kubectl, gh, helm, terraform's
# wrapper, argocd, istioctl — are not. They call two helper functions that live
# in the `bash-completion` *package*, not in bash:
#
#     _get_comp_words_by_ref   splits the command line into cur/prev/words/cword
#     _filedir                 adds filename candidates to COMPREPLY
#
# On Linux the distro installs that package. On Windows there is nothing to
# install: Git for Windows does not ship it either, so `docker completion bash`
# sources cleanly there and then silently completes nothing. Defining the two
# helpers is the whole fix, and it is ~40 lines.
#
# These are sourced before the user's rc files, so a user who does install
# bash-completion gets theirs instead: a later definition simply wins.

# Split the current command line, assigning to whichever of cur/prev/words/cword
# the caller names. Assignment reaches the caller's `local` variables by the
# same dynamic scoping bash-completion's own version relies on.
#
# Derived from COMP_LINE and COMP_POINT rather than from COMP_WORDS, because the
# cursor position is what decides where the current word ends, and because the
# caller invariably passes `-n =:` — "do not break words on = or :" — which is
# exactly what splitting the raw line on whitespace gives.
#
# Known limitation, stated rather than hidden: word splitting here is on
# whitespace only. A quoted argument containing a space is seen as two words.
# Completion still works; the request sent to the tool is merely split where the
# quote would have held it together.
_get_comp_words_by_ref()
{
    local OPTIND=1 _cash_flag
    # -n/-c/-i/-w are accepted for compatibility. Only the variable names that
    # follow them affect what this assigns.
    while getopts "n:c:i:w:" _cash_flag "$@"; do :; done
    shift $((OPTIND - 1))

    local _cash_line=${COMP_LINE-}
    local _cash_point=${COMP_POINT-${#_cash_line}}
    local _cash_before=${_cash_line:0:_cash_point}

    local -a _cash_words=()
    read -ra _cash_words <<< "$_cash_before"

    local _cash_cur=""
    if [[ -n $_cash_before && $_cash_before != *[[:space:]] && ${#_cash_words[@]} -gt 0 ]]; then
        # The cursor is inside the last word: that word is the one being completed.
        _cash_cur=${_cash_words[${#_cash_words[@]} - 1]}
    else
        # A trailing space means a new, still-empty word has been started.
        _cash_words+=("")
    fi

    local _cash_cword=$((${#_cash_words[@]} - 1))
    local _cash_prev=""
    if ((_cash_cword > 0)); then
        _cash_prev=${_cash_words[_cash_cword - 1]}
    fi

    while (($# > 0)); do
        case $1 in
            cur) cur=$_cash_cur ;;
            prev) prev=$_cash_prev ;;
            words) words=("${_cash_words[@]}") ;;
            cword) cword=$_cash_cword ;;
        esac
        shift
    done

    return 0
}

# Prepare the standard completion variables. Cobra's scripts probe for this with
# `declare -F` and fall back to their own copy when it is absent, so defining it
# is optional — but a tool that calls it unconditionally should find it.
_init_completion()
{
    local OPTIND=1 _cash_flag _cash_exclude=""
    while getopts "n:e:o:i:s" _cash_flag "$@"; do
        case $_cash_flag in
            n) _cash_exclude=$OPTARG ;;
            *) ;;
        esac
    done

    COMPREPLY=()
    _get_comp_words_by_ref -n "$_cash_exclude" cur prev words cword
    return 0
}

# Append filename candidates for the current word. The real version filters by
# extension pattern; the argument is accepted and, apart from -d, ignored —
# over-offering a candidate is a far smaller sin than offering none.
_filedir()
{
    local IFS=$'\n'
    local -a _cash_candidates=()

    if [[ ${1-} == -d ]]; then
        _cash_candidates=($(compgen -d -- "${cur-}"))
    else
        _cash_candidates=($(compgen -f -- "${cur-}"))
    fi

    if ((${#_cash_candidates[@]} > 0)); then
        COMPREPLY+=("${_cash_candidates[@]}")
    fi

    return 0
}
