# grep cases, run under GNU grep 3.12 (the oracle) and under cash's builtin. Output
# that could hide a byte goes through od, so line endings, NULs, tabs and colour
# sequences are all visible. grep_cases.out is GNU grep 3.12's output.
#
# The locale is C.UTF-8 rather than C: cash's grep reads UTF-8 by nature, and GNU
# grep's `-i`, `.`, `\w` and its binary-file test all depend on the locale. Files
# found under a directory go through `sort`, since GNU grep takes them in the file
# system's order and cash in name order.
#
# Regenerate the golden file (WSL):
#   bash grep_cases.sh > grep_cases.out 2>&1

exec 2>&1 </dev/null
export LC_ALL=C.UTF-8
export GREP_COLORS='ms=01;31:mc=01;31:sl=:cx=:fn=35:ln=32:bn=32:se=36'
unset GREP_COLOR
dir=$(mktemp -d)
cd "$dir" || exit 1
show() { od -An -c | sed 's/  */ /g; s/ *$//'; }
rc() { echo "rc=$?"; }

printf 'foo\nbar\nbaz\nfoo bar\n' > t
printf 'a\0b\nfoo\n' > bin
printf 'foo\nbar\n' > p
printf '1\n2\nfoo\n4\n5\n6\nfoo\n8\n9\n10\nfoo\n' > ctx
mkdir -p r/sub/deep r/.hid d
printf 'foo\n' > r/a.txt; printf 'foo\n' > r/b.c; printf 'foo\n' > r/sub/c.txt
printf 'foo\n' > r/sub/deep/d.txt; printf 'foo\n' > r/.hid/e.txt; printf 'foo\n' > r/.f
printf 'foo\n' > d/x

echo "== plain"; grep foo t; rc
echo "== no match"; grep zzz t; rc
echo "== stdin"; printf 'foo\nbar\n' | grep bar; rc
echo "== -c"; grep -c foo t; grep -c zzz t; rc
echo "== -v"; grep -v foo t; echo "-- -vc"; grep -vc foo t
echo "== -n"; grep -n foo t; echo "-- -nv"; grep -nv foo t
echo "== -i"; printf 'FOO\nfoo\nFoO\n' | grep -ci foo; printf 'ÉCOLE\nécole\nÉcole\nStraße\n' | grep -i école; printf 'Σ σ ς\n' | grep -o -i 'σ'; printf 'K k K\n' | grep -oi 'k'; echo "-- --no-ignore-case"; printf 'FOO\nfoo\n' | grep -i --no-ignore-case foo; echo "-- -i class"; printf 'FOO\nfoo\n' | grep -i '[f]oo'; printf 'FOO\n' | grep -i '[^f]oo'; rc; echo "-- -i backref"; printf 'aA\nab\n' | grep -i '\(a\)\1'; echo "-- -i -F"; printf 'FOO\nfoo\n' | grep -iF foo; printf 'ÉCOLE\n' | grep -iF école
echo "== -w"; printf 'foo foobar\nfoobar\n_foo\nfoo_\nfoo-bar\n-foo-\n' | grep -nw foo; echo "-- -ow"; printf 'foobar foo foo\n' | grep -ow foo; echo "-- -w empty"; printf 'foo\n\n' | grep -nw ''; rc; echo "-- -w nonword"; printf 'a-b\nab\n' | grep -w -- '-'; rc; printf 'a - b\n' | grep -ow -- '-'; echo "-- -w inside"; printf 'foofoo foo\n' | grep -ow 'foo'; echo "-- -w -x"; printf 'foo\nfoo bar\n' | grep -wx foo; echo "-- -w unicode"; printf 'éfoo\nfoo é\n' | grep -w foo; echo "-- -w alternation"; printf 'abc\n' | grep -ow 'a\|ab\|abc'; printf 'abcd\n' | grep -owE 'a|ab|abc'; rc; printf 'abc d\n' | grep -owE 'abc|abc d'; echo "-- -w empty match"; printf 'ab\n' | grep -cw 'x*'; printf 'a \n' | grep -cw 'x*'; printf 'ab\n' | grep -ow 'a*'; rc; printf 'fooo foo\n' | grep -ow 'fo*'
echo "== -x"; printf 'foo\nfoobar\nfoo\n' | grep -nx foo; echo "-- -xo"; printf 'foo\n' | grep -xo 'f.*'; echo "-- -x empty"; printf '\nfoo\n' | grep -nx ''; echo "-- -x alternation"; printf 'foo\nbar\nfoobar\n' | grep -x -e foo -e bar; printf 'foo\nbar\nfoobar\n' | grep -xE 'foo|bar'; printf 'ab\n' | grep -xo 'a\|ab'
echo "== -o"; printf 'xfoo foo\n' | grep -o foo; echo "-- -o multiple patterns"; printf 'fooXbar\n' | grep -o -e foo -e bar; printf 'foobar\n' | grep -o -e bar -e foo; echo "-- -o longest"; printf 'ab\n' | grep -o 'a\|ab'; printf 'abab\n' | grep -oE 'a|ab'; printf '3.14\n' | grep -oE '[0-9]+|[0-9]+\.[0-9]+'; printf 'xyz\n' | grep -oE 'x|xy|xyz'; printf 'ab\n' | grep -oF -e a -e ab; printf 'aaa\n' | grep -oE 'a|aa'; printf 'abc\n' | grep -oE '(a|ab)(c|bc)'; echo "-- -o empty matches"; printf 'abc\n' | grep -o 'b*'; printf 'abc\n' | grep -o ''; rc; printf 'abc\n' | grep -on 'x*'; rc; printf 'abc\nabc\n' | grep -on 'x*\|b'; printf 'abcbc\n' | grep -oE '(bc)*'; printf 'abc\n' | grep -oE '^|c'; echo "-- -o anchors"; printf 'abc\n' | grep -o '^.'; printf 'abc\n' | grep -o '.$'; printf 'a b c\n' | grep -o '\<.'; printf 'a b c\n' | grep -o '.\>'; echo "-- -ov"; printf 'foo\nbar\n' | grep -ov foo; rc; printf 'foo\nbar\n' | grep -ovc foo; echo "-- -o -i"; printf 'FOO foo\n' | grep -oi foo
echo "== -b"; printf 'ab\nfoo\n' | grep -b foo; printf 'xfoo foo\n' | grep -ob foo; printf 'xx\nfoo foo\n' | grep -nbo foo; printf 'é foo\n' | grep -bo foo; printf 'ab\nfoo\ncd\n' | grep -nb -C1 foo
echo "== -H -h"; grep -H foo p; grep -h foo t p; grep foo t p; grep -Hh foo t p; grep -hH foo t p; grep -Hn foo p; grep -Hbn foo p; grep -Hc foo p; grep -c foo t p; grep -ch foo t p
echo "== -l -L"; grep -l foo t p bin d/x; rc; grep -l zzz t; rc; grep -L foo t p bin; rc; grep -L zzz t; rc; grep -L baz t p; rc; grep -lv foo p; rc; grep -lv bar p; rc; grep -lc foo t p; grep -lL foo t; grep -Ll foo t; echo "-- -l with -o -n -b"; grep -lo foo t; grep -ln foo t; grep -lb foo t
echo "== -q -s"; grep -q foo t; rc; grep -q zzz t; rc; grep -q foo nosuch; rc; grep -q foo nosuch t; rc; grep -q foo t nosuch; rc; grep -qs foo nosuch; rc; grep -q '\(' t; rc; grep -qc foo t; rc; grep -qv foo t; rc; echo "-- -s"; grep -s foo nosuch t; rc; grep -s foo d; rc; grep -s '\(' t; rc; grep foo nosuch; rc; grep foo d; rc; grep -c foo d; rc; grep -c foo d p; rc; grep -L foo d p; rc; grep -c foo nosuch p; rc
echo "== -m"; grep -m 1 foo t; grep -m 0 foo t; rc; grep -m -1 foo t; grep -c -m 1 . t; grep -m 1 -c -v foo t; printf 'foo\nbar\nfoo\n' | grep -m 1 -A 1 foo; printf 'foo\nfoo\nx\n' | grep -n -A1 -m1 foo; printf 'foo\nfoo\nx\n' | grep -c -A1 -m1 foo; printf 'foo\na\nfoo\nb\n' | grep -B1 -m1 foo; printf 'foo\nx\ny\nfoo\n' | grep -A2 -m1 foo; grep -l -m 0 foo t; rc; grep -m 99999999999999999999 foo t; grep -m +1 foo t; grep -m ' 1' foo t
echo "== context"; grep -A1 foo ctx; echo "-- -B1"; grep -B1 foo ctx; echo "-- -C1"; grep -C1 foo ctx; echo "-- -2"; grep -2 foo ctx; echo "-- -nC1"; grep -nC1 foo ctx; echo "-- -nbC1"; grep -nbC1 foo ctx; echo "-- -HC1"; grep -HC1 foo ctx; echo "-- separator"; grep --group-separator=XX -A1 foo ctx; grep --no-group-separator -A1 foo ctx; grep --group-separator= -A1 foo ctx; grep --group-separator XX -A1 foo ctx | head -3; echo "-- -A0"; grep -A0 foo ctx; echo "-- -C0"; grep -C0 foo ctx; echo "-- -c -o -v with context"; grep -c -C1 foo ctx; grep -o -C1 foo ctx; grep -v -A1 foo ctx; echo "-- overlap"; printf 'foo\nx\nfoo\ny\nz\nfoo\n' | grep -A1 foo; echo "-- explicit wins"; grep -2 -A0 foo ctx; grep -A0 -2 foo ctx; grep -C1 -A3 foo ctx; grep --context=1 --context=0 foo ctx; grep -A1 -A0 foo ctx; echo "-- -12"; printf 'foo\n' | grep -12 foo; grep -1 -2 foo ctx; echo "-- edges"; printf 'foo\n' | grep -C2 foo; printf 'a\nfoo\nb\nc\nfoo\n' | grep -nA1 foo; printf 'foo\nfoo\nfoo\n' | grep -nC1 foo; printf 'foo\na\nb\nfoo\n' | grep -nC1 foo; printf 'foo\na\nb\nc\nfoo\n' | grep -nC1 foo; printf 'a\nb\nfoo\nc\nd\n' | grep -n -v -C1 '[ab]'; echo "-- across files"; printf 'foo\nx\n' > c1; printf 'y\nfoo\n' > c2; grep -A1 foo c1 c2; echo "--"; grep -B1 foo c1 c2; echo "--"; grep -C1 foo c2 c1 c2; echo "--"; grep -C1 -c foo c1 c2; echo "--"; grep -nC1 foo c1 c2 c1; echo "-- -A invalid"; grep -A x foo t; rc; grep -A -1 foo t; rc; grep --context foo t; rc; grep -A 1k foo t; rc; grep -A 99999999999999999999 foo t; rc
echo "== -e -f"; grep -e foo -e bar t; grep -f p t; : > empty; grep -f empty t; rc; grep -c -f empty -e zzz t; grep -v -f empty t | head -1; printf '\n' > nl; grep -c -f nl t; grep -efoo t; grep --regexp=foo t; grep --regex=foo t; grep --file=p t; printf 'foo\nbar\n' | grep 'foo
bar'; printf 'a\nb\n' | grep -F 'a
b'; grep -f - t < p; printf 'f*o\n' > fs; printf 'f*o\nfoo\n' | grep -F -f fs; printf 'foo\n' | grep -F -e ''; rc; printf 'foo\n' | grep -c -F -e '' -e zz; printf 'a\nb\n' | grep -F -e a -e ''; grep -f nosuch t; rc; grep -e; rc; grep -e foo -e; rc
echo "== -F"; printf 'a.b\naxb\na[b\na\\b\na^b\n$a\n' > sp; grep -F 'a.b' sp; grep -F 'a[' sp; grep -F 'a\' sp; grep -F '^' sp; grep -Fx '$a' sp; grep -Fo '.' sp; grep -Fc '' sp; printf 'foo\n' | grep -Fw 'fo'; rc; printf 'fo o\n' | grep -Fw 'fo'; printf 'a b\n' | grep -F 'a b'; printf 'aaa\n' | grep -Fo 'aa'; printf 'tab\there\n' | grep -F "$(printf 'b\t')" | show; printf 'a--b\n' | grep -Fow -- '-'; rc
echo "== BRE"; printf 'ab\naab\nabab\n' | grep -x '\(ab\)\{2\}'; printf 'a\nab\nabb\n' | grep -x 'ab\{1,2\}'; printf 'a\nab\nabb\n' | grep -x 'ab\{2,\}'; printf 'a\nab\n' | grep -x 'ab\?'; printf 'a\nab\nabb\n' | grep -x 'ab\+'; printf 'a\nb\nc\n' | grep -x 'a\|b'; printf 'a\nab\n(a)\n' | grep '(a)'; printf 'a{1}\na\n' | grep 'a{1}'; printf 'a|b\n' | grep 'a|b'; printf 'a?\n' | grep 'a?'; printf 'a+\n' | grep 'a+'; printf '*a\na\n' | grep '*a'; printf '*a\na\n' | grep -c '^*a'; printf '*\n' | grep -x '\(*\)'; printf 'ab\n' | grep -o '\(a\)\(b\)'; printf 'a^b\n' | grep 'a^b'; printf 'a$b\n' | grep 'a$b'; printf 'ab\n' | grep -c '^a\|^b'; printf 'ab\n' | grep -o '\(^a\)'; printf 'ab\n' | grep -o 'b\($\)'; printf 'a.b\naxb\n' | grep 'a\.b'; printf 'a\\b\n' | grep 'a\\b'; printf 'a/b\n' | grep 'a\/b'; printf 'aXb\n' | grep 'a\Xb'; printf 'a\n' | grep -o 'a\{0\}'; rc; printf 'aaa\n' | grep -o 'a\{2\}'; printf 'aaa\n' | grep -o 'a\{,\}'; printf 'ab\n' | grep -o 'a\{1\}*'; printf 'aXb\n' | grep -o 'a.\{1\}b'; printf 'ab\n' | grep -o '\(a\)*b'; printf 'ab\n' | grep -o 'a\(\)b'; printf 'ab\n' | grep -o 'a**b'; printf 'ab\n' | grep -o '\(a\|b\)\{2\}'; printf 'a}\n' | grep 'a\}'; printf 'a\n' | grep -c '\{1\}'; printf 'foo\n' | grep -o '\`foo'; printf "foo\n" | grep -o "foo\\'"
echo "== backreferences"; printf 'abcabc\n' | grep -o '\(abc\)\1'; printf 'abab\nabba\n' | grep '\(a\)\(b\)\2\1'; printf 'aa\nab\n' | grep -E '(a)\1'; printf 'aa\nab\n' | grep -E '(a)\1|b'; printf 'ab\nabab\n' | grep -E -x '(ab)+'; printf 'xaax\n' | grep -o '\(a\)\1'; printf 'abab ababx\n' | grep -ow '\(ab\)\1'; printf 'aA\n' | grep -ic '\(a\)\1'; printf 'abcabc\n' | grep -c -e '\(abc\)\1' -e '\(c\)\1'
echo "== ERE"; printf 'ab\nabab\n' | grep -E -x '(ab){2}'; printf 'a{1,2}\n' | grep -E 'a\{1,2\}'; printf 'a{\n' | grep -E 'a{'; printf 'a{1\n' | grep -E 'a{1'; printf 'a{1,\n' | grep -E 'a{1,'; printf 'a{x}\n' | grep -oE 'a{x}'; printf 'a{1x}\n' | grep -oE 'a{1x}'; printf 'aaa\n' | grep -oE 'a{,}'; printf 'aaa\n' | grep -oE 'a{,2}'; printf 'aa\n' | grep -oE 'a{01}'; printf 'a}\n' | grep -E 'a}'; printf '(\n' | grep -E '\('; printf 'a\n' | grep -E 'a|'; printf 'xa\n' | grep -oE '(|a)'; printf 'ab\n' | grep -E -o 'a?b'; printf 'ab\n' | grep -oE 'a+?'; printf 'aa\n' | grep -oE 'a*?'; printf 'aaa\n' | grep -oE 'a{2}?'; printf 'ab\n' | grep -oE 'a**b'; printf 'ab\n' | grep -oE 'a()b'; printf 'ab\n' | grep -oE 'a{1}{2}b'; rc; printf 'ab\n' | grep -cE 'a^b'; printf 'a^b\n' | grep -cE 'a\^b'; printf 'ab\n' | grep -cE 'a$b'; printf 'ab\n' | grep -cE '(^a)(b$)'; printf 'ab\n' | grep -cE '^(a|^b)'; printf ')\n' | grep -E ')'; printf 'foo\nbar\n' | grep -E '*a'; printf 'foo\nbar\n' | grep -E '+a'; printf 'foo\nbar\n' | grep -E '?a'; printf 'foo\nbar\n' | grep -E '{1}'; printf 'foo\nbar\n' | grep -cE '^*'; printf 'foo\nbar\n' | grep -E 'a||b'; printf 'x\n' | grep -E '(|a)'
echo "== classes"; printf 'foo bar\nfoobar\n' | grep -o '\<bar'; printf 'foo bar\nfoobar\n' | grep -o 'foo\>'; printf 'foo bar\n' | grep -o '\bbar\b'; printf 'foobar\n' | grep -o 'o\Bb'; printf 'a_1 b-2\n' | grep -o '\w*'; printf 'a_1 b-2\n' | grep -o '\W'; printf 'a \tb\n' | grep -o '\s' | show; printf 'a \tb\n' | grep -o '\S*'; printf 'éa\n' | grep -o '\w*'; printf 'é a\n' | grep -o '\<a'; printf 'foo bar\n' | grep -E -o '\<bar'; printf 'a_b\n' | grep -o '\<\w'; printf 'a.b\n' | grep -o '[[:punct:]]'; printf 'aB3 \n' | grep -o '[[:upper:][:digit:]]'; printf 'a]b\n' | grep -o '[]]'; printf 'a]b\n' | grep -o '[^]a]'; printf 'a-b\n' | grep -o '[a-]'; printf 'a\\b\n' | grep -o '[\\]'; printf 'a\\b\n' | grep -o '[\]'; printf 'a.b\n' | grep -o '[.]'; printf 'a\n' | grep -o '[[.a.]]'; printf 'a\n' | grep -o '[[=a=]]'; printf 'a^b\n' | grep -o '[a^]'; printf 'a\n' | grep -o '[[:alpha:]-]'; printf 'é\n' | grep -o '[[:alpha:]]'; printf 'é\n' | grep -o '[a-z]'; rc; printf 'w\n' | grep -o '[\w]'; printf 'a\n-\n]\n^\n' | grep -c '[]-a]'; printf '%%\n-\n*\n.\n' | grep -c '[%%--]'; printf 'aé b\n' | grep -o '[[:alpha:]]*'; printf 'aé1_\n' | grep -o '[[:alnum:]]*'; printf 'a\tb c\n' | grep -o '[[:blank:]]' | show; printf 'a\tb\n' | grep -o '[[:cntrl:]]' | show; printf 'ab 1\n' | grep -o '[[:graph:]]*'; printf 'ab 1\n' | grep -o '[[:print:]]*'; printf 'AbC\n' | grep -o '[[:lower:]]'; printf 'g9f\n' | grep -o '[[:xdigit:]]*'; printf 'a b\n' | grep -o '[[:space:]]' | show
echo "== dot and multibyte"; printf 'é\nab\n' | grep -x '.'; printf 'é\nab\n' | grep -x '..'; printf 'aéb\n' | grep -o 'a.b'; printf 'aéb\n' | grep -o '[^a]'; printf 'aé\n' | grep -ob '.'
echo "== bad patterns"; for pat in '\(' 'a\{1' '[a' '\1' 'a\{2,1\}' '\)' '[[:foo:]]' '[b-a]' 'a\{99999\}' '\(a\)\2' 'a\{1,2' 'a\{\}' '[' '[^' 'a\' '[[:space:]-a]' '[[.hyphen.]]' 'a\{ 1\}'; do echo "pat=$pat"; grep "$pat" t; rc; done; for pat in '(' '[a' '(a)\2' 'a{2,1}' '\' 'a{}' 'a{1,2,3}' 'a{32768}'; do echo "pat=-E $pat"; grep -E "$pat" t; rc; done
echo "== warnings"; printf 'a/b\n' | grep -c 'a\/b'; printf 'a-b\n' | grep -c 'a\-b'; printf 'a b\n' | grep -c 'a\ b'; printf 'a0\n' | grep -c 'a\0'; printf 'a\n' | grep -c '\{'; printf 'a\n' | grep -E -c '\{'; printf 'a\n' | grep -c '\<'; printf 'a\n' | grep -c '[\a]'
echo "== usage"; grep; rc; grep -E; rc; grep -y FOO t; rc; grep --foo x t; rc; grep --co foo t; rc; grep --col foo t; rc; grep --lin foo t; rc; grep --line-n foo t; grep -m x foo t; rc; grep --binary-files=foo x t; rc; grep -d foo x t; rc; grep -d rec foo d; grep -D foo x t; rc; grep -D skip foo t; grep --colour foo t; grep -X foo t; rc; grep -e foo -X t; rc; grep -X egrep 'fo+' t; grep --help=x; rc; grep --regexp; rc; grep -E -F foo t; rc; grep -F -E foo t; rc; grep -G -E 'fo+' t; rc; grep foo -- -t; rc; grep -- foo t; printf -- '-x\n' | grep -e -x; printf -- '-x\n' | grep -- -x; grep -k foo t; rc; grep --exclude-from=nosuch foo t; rc; grep -u foo t; rc; grep --color=foo x t | head -2; rc; grep --version | head -1; grep -V | head -1; grep --help | head -3
echo "== long options"; grep --extended-regexp 'fo+' t; grep --fixed-strings foo t; grep --basic-regexp foo t; grep --ignore-case FOO t; grep --invert-match foo t; grep --word-regexp foo t; grep --line-regexp foo t; grep --count foo t; grep --files-with-matches foo t; grep --files-without-match foo t; rc; grep --max-count=1 . t; grep --only-matching fo t; grep --quiet foo t; rc; grep --silent foo t; rc; grep --no-messages foo nosuch; rc; grep --byte-offset foo t; grep --with-filename foo t; grep --no-filename foo t p; grep --line-number foo t; grep --initial-tab -n foo t | show; grep --null -l foo t | show; grep --after-context=1 foo t; grep --before-context=1 bar t; grep --context=1 baz t; grep --text foo bin | show; grep --recursive foo d; grep --dereference-recursive foo d; grep --null-data foo p | show; grep --file p t; grep --regexp foo t; grep --max 1 foo t; grep --after 1 foo t; grep --label=X -H foo - < t; grep --line-buffered foo t; grep --no-ignore-case FOO t; rc; grep --binary foo t; grep --fixed-regexp foo t; grep --unix-byte-offsets foo t; grep --directories recurse foo d; grep --devices read foo t
echo "== clusters"; grep -nic FOO t; grep -ofoo t; rc; grep -oefoo t; grep -nefoo t; grep -A1n foo ctx | head -2; grep -nA1 foo ctx | head -2; grep -m1n . t; grep -1n foo ctx | head -2; grep -n1 foo ctx | head -2; grep -e foo -ie BAR t; grep -ffoo t; rc; grep -f p -e zzz t | head -2; grep -Ee 'fo+' t; grep -c0 foo t; grep -0 foo t; grep -5c foo ctx; grep -m 1 -m 2 . t; grep -A 1 -A 2 foo ctx | head -4; grep -c -q foo t; rc; grep -c -o foo t; grep -lcH foo t; grep -L -c foo t; rc; grep -oH foo p; grep -oHn foo p; grep -vx foo t; grep -vw foo t; grep -vi FOO t; grep -vm1 foo t; grep -vm1c foo t; grep -v -e foo -e bar t; rc; grep -v '' t; rc; grep -vx '' t; grep -cv '' t; grep -v -F '' t; rc
echo "== -T"; printf 'foo\n' | grep -T foo | show; printf 'foo\n' | grep -Tn foo | show; printf 'foo\n' | grep -TH foo | show; printf 'foo\n' | grep -THn foo | show; printf 'foo\n' | grep -THnb foo | show; printf 'foo\n' | grep -Tb foo | show; printf 'foo\n' | grep -Tc foo | show; printf 'foo\n' | grep -Tl foo | show; printf 'foo\n' | grep -To foo | show; printf 'foo\n' | grep -Ton foo | show; printf 'foo\nbar\n' | grep -TnA1 foo | show; printf 'foo\nbar\n' | grep -THA1 foo | show; seq 1 12 | grep -Tn 1 | show; printf '\n' | grep -Tn '' | show; printf 'foo\n' | grep -THnZ foo | show; printf 'foo\n' | grep -TlZ foo | show; printf 'foo\n' | grep -T -c -H foo | show; printf 'foo\n' | grep -T -o -b foo | show
echo "== -Z"; grep -Zl foo t d/x | show; grep -Z foo p d/x | show; grep -Zc foo p d/x | show; grep -ZL zzz t | show; grep --null -n foo p d/x | show
echo "== -z"; printf 'foo\0bar\0baz foo' | grep -z foo | show; printf 'foo\0bar\0baz foo' | grep -zo foo | show; printf 'foo\0bar\0baz foo' | grep -zc foo; printf 'foo\0bar\0' | grep -z -c '^bar'; printf 'foo\0bar\0' | grep -z -c 'foo$'; printf 'foo\nbar\0' | grep -z -c 'foo.bar'; printf 'foo\nbar\0' | grep -z -c 'foo\sbar'; printf 'foo\nbar\0' | grep -z -c -x 'foo'; printf 'foo\nbar\0' | grep -z -o 'o\nb' | show; printf 'x\nfoo\n' | grep -zb foo | show; printf 'foo\n' | grep -nz foo | show; printf 'fo\xc3\xa9\0' | grep -z -c -x 'fo.'
echo "== --label and stdin"; printf 'foo\n' | grep -H --label=LBL foo; printf 'foo\n' | grep -c --label=LBL foo t -; printf 'foo\n' | grep -l foo -; printf 'foo\n' | grep foo - t; printf 'foo\n' | grep -L zzz -; printf 'foo\n' | grep -c foo t -; grep foo - - < p; printf '' | grep -c x; rc; printf '' | grep -L x -; rc
echo "== no final newline"; printf 'foo' | grep foo | show; printf 'foo' | grep -c foo; printf 'a\nfoo' | grep -n foo | show; printf 'foo' | grep -o o | show; printf 'foo' | grep -v x | show; printf '' | grep -v x; rc; printf '\n' | grep -c ''; printf '' | grep ''; rc
echo "== empty lines"; printf 'a\n\nb\n' | grep -n '^$'; printf 'a\n\nb\n' | grep -c ''; printf 'a\n\nb\n' | grep -o ''; rc
echo "== binary"; grep foo bin; rc; grep -c foo bin; grep -l foo bin; grep -o foo bin; grep -n foo bin; grep -q foo bin; rc; grep -v zzz bin; rc; grep -s foo bin; rc; grep -sq foo bin; rc; grep zzz bin; rc; echo "-- without-match"; grep --binary-files=without-match foo bin; rc; grep -I foo bin p; rc; grep -Ic foo bin p; rc; grep -Il foo bin p; rc; grep -IL foo bin p; rc; echo "-- text"; grep --binary-files=text foo bin | show; grep -a foo bin | show; grep -ac foo bin; grep -U foo bin; rc; printf 'a\0b\n' | grep -a -o 'a.b' | show; printf 'a\0b\n' | grep -a -c '^b'; printf 'a\0b\n' | grep -a -c 'a\>'; echo "-- NUL splits lines"; printf 'foo\0foo\n' | grep -c foo; printf 'a\0b\n' | grep -c '^b'; printf 'a\0b\n' | grep -c 'a$'; printf 'foo\0foo\n' | grep -c -x foo; printf 'a\0b\n' | grep -c 'a.b'; printf 'bar\n\0\n' | grep -c ''; printf 'bar\n\0\n' | grep -c '^$'; printf '\0\0' | grep -c '^$'; printf 'foo\n\0\nfoo\n' | grep -c foo; printf 'foo\n\0\nfoo\n' | grep -n foo; rc; printf 'foo\n\0\nfoo\n' | grep -l foo; printf 'bar\n\0\nfoo\n' | grep -v foo; rc; printf 'x\0' | grep x; rc; printf 'x\0' | grep -c x; printf 'x\0y' | grep -c '^y$'; printf '\0\n' | grep -c x; rc; echo "-- encoding errors"; printf 'foo\xff\nfoo\n' | grep foo; rc; printf 'foo\xff\nfoo\n' | grep -n foo; printf 'bar\xff\nfoo\n' | grep foo; printf 'foo\xff\nfoo\n' | grep -c foo; printf 'foo\xff\nfoo\n' | grep -a foo | show; printf 'foo\xff\nfoo\n' | grep -o foo; printf 'foo\xff\nfoo\n' | grep -o 'o.'; printf 'foo\xff\nfoo\n' | grep -v zzz; printf 'xx\xff\nfoo\n' | grep -B1 foo; printf 'foo\nbar\xff\n' | grep -A1 foo; printf '\xff\n' | grep -c .; printf '\xff\n' | grep -x '.'; rc; printf 'a\xffb\n' | grep -o 'a.b'; rc; printf 'a\xffb\n' | grep -o '.' | show; printf 'a\xffb\n' | grep -ob '.' | show; printf 'a\xffb\n' | grep -c 'a.*b'; printf 'a\xffb\n' > rawpat; printf '\xff\n' > rawbyte; printf 'a\xff\n' > rawpre; printf 'a\xffb\n' | grep -c -f rawpat; printf 'a\xffb\n' | grep -c -F -f rawbyte; printf 'a\xffb\n' | grep -c -x -f rawpat; printf 'a\xffb\n' | grep -ao -f rawpre | show; printf '\xff\n' | grep -c '^.*$'; printf '\xffa\n' | grep -o 'a'; printf 'foo\x80\0' | grep -z -c foo; printf 'foo\xff\0' | grep -z foo; rc
echo "== color"; printf 'foo bar foo\n' | grep --color=always foo | show; printf 'foo\n' | grep --color=always -n foo | show; printf 'foo\n' | grep --color=always -H foo | show; printf 'foo\n' | grep --color=always -Hnb foo | show; printf 'foo\n' | grep --color=always -o foo | show; printf 'xfooy\n' | grep --color=always -o foo | show; printf 'foo\n' | grep --color=always -v bar | show; printf 'foo\nbar\n' | grep --color=always -v foo | show; printf 'foo\nbar\n' | grep --color=always -A1 foo | show; printf 'foo\nbar\n' | grep --color=always -nA1 foo | show; printf 'foo\nbar\n' | grep --color=always -HnA1 foo | show; printf 'foo\n' | grep --color=always -c foo | show; grep --color=always -c foo p bin | show; grep --color=always -l foo t | show; grep --color=always -L zzz t | show; grep --color=always -Zl foo t | show; printf 'foo\nbar\nx\nfoo\n' | grep --color=always -A1 foo | show; printf 'foo\nbar\nx\nfoo\n' | grep --color=always --group-separator=XX -A1 foo | show; printf 'foo\n' | grep --color=always -x foo | show; printf 'foo\n' | grep --color=always 'o*' | show; printf 'foo\n' | grep --color=always 'x*' | show; printf 'foo\n' | grep --color=always -i FOO | show; printf 'foo\n' | grep --color=always -E 'f|o' | show; printf 'foo\n' | grep --color=always -w foo | show; printf 'foo\n' | grep --color=always -F oo | show; printf 'foo\n' | grep --color=always -T -n foo | show; printf 'foo\nbar\n' | grep --color=always -v -A1 foo | show; printf 'foo\nbar\n' | grep --color=always -v -o foo | show; printf 'foo\n' | grep --color=always -nz foo | show; printf 'foo\n' | grep --colour=always foo | show; printf 'foo\n' | grep --color foo | show; printf 'foo\n' | grep --color=never foo | show; printf 'foo\n' | grep --color=auto foo | show; printf 'ab\n' | grep --color=always -E 'a|ab' | show; printf 'aaa\n' | grep --color=always 'a' | show; printf 'xfoox\n' | grep --color=always -b foo | show; printf 'xfoox\n' | grep --color=always -ob foo | show; printf 'xfoox\n' | grep --color=always -bo 'x' | show; printf 'foo\n' | grep --color=always -e foo -e zz | show; printf 'foo\n' | grep --color=always -e o -e fo | show; printf 'foobar foo\n' | grep --color=always -w foo | show; grep --color=always -r foo d | show; printf 'foo\n' | grep --color=always -H --label=L foo | show; printf 'foo\n' | grep --color=always -THnb foo | show; printf 'a \n' | grep --color=always -w 'x*' | show; printf 'foo\n\0\n' | grep --color=always foo; printf 'foo\xff\n' | grep --color=always foo
echo "== GREP_COLORS"; c() { printf "$1" | GREP_COLORS="$2" grep --color=always "${@:3}" | show; }; c 'foo\n' 'ms=1;32' foo; c 'foo\n' 'ms=1;32:ne' foo; c 'foo\nbar\n' 'sl=1:cx=2' -A1 foo; c 'foo\nbar\n' 'sl=1:cx=2:rv' -v -A1 foo; c 'foo\nbar\n' 'sl=1:cx=2' -v -A1 foo; c 'foo\nbar\n' 'mt=4' -A1 foo; c 'foo\nbar\n' 'mc=4' -v -B1 bar; c 'foo\nbar\n' 'ms=4:mc=5' -v -B1 bar; c 'foo\n' 'fn=1:se=2' -H foo; c 'foo\n' 'fn=:se=' -H foo; c 'foo\n' 'ms=' foo; c 'foo\n' 'bogus' foo; c 'foo\n' 'ms=1;' foo; c 'foo\n' 'ms=1:bogus=2:ln=3' -n foo; c 'foo\n' 'ms=1x' foo; c 'foo\n' '' foo; c 'foo\n' 'sl=1' -c foo; c 'xfoox\n' 'sl=1' foo; c 'xfoox\n' 'sl=1:ms=' foo; c 'xfooxfoox\n' 'sl=1' foo; c 'foo\n' 'sl=1' -o o; c 'foo\n' 'sl=1' 'x*'; c 'foo\n' 'sl=1' -E 'x*|o'; c 'foo\n' 'sl=1' -n foo; c 'foo\n' 'sl=1:ln=:se=' -n foo; c 'foo\n' 'sl=1:ms=:ne' -n foo; c 'foo\nbar\n' 'sl=1:cx=2:ne' -A1 -n foo; c 'foo\nbar\n' 'sl=1:cx=2:rv=1' -v -A1 foo; c 'foo\nbar\n' 'sl=1:cx=2:' -v -A1 foo; c 'foo\nbar\n' ':sl=1' -v -A1 foo; c 'foo\nbar\n' 'sl=1;;2' -v -A1 foo; c 'foo\nbar\n' 'sl=1:sl=2' -v -A1 foo; c 'foo\nbar\n' 'sl=1:cx=2:ms=1x' -v -A1 foo; c 'foo\nbar\n' 'sl=1:ms=1:cx=2' -v -A1 -n -H foo; c 'foo\nbar\n' 'sl=1:ms=1:cx=2' -v -A1 -T -n foo; c 'foo\nbar\n' 'sl=1:ms=1:cx=2:se=3' -o -n -A1 foo; c 'foo\nbar\n' 'sl=1:ms=1:cx=2:se=3' -n -A1 -H -b foo; c 'foo\nbar\nxx\nfoo\n' 'sl=1:ms=1:cx=2:se=3' -A1 foo; c 'foo\nbar\nxx\nfoo\n' 'sl=1:ms=1:cx=2:se=' -A1 foo; c 'foo\n' 'fn=1:se=2' -Zl foo; c 'foo\n' 'fn=1:se=2' -ZH foo; c 'foo\n' 'fn=1:se=2' -ZHn foo; c 'foo\n' 'fn=1:se=2' -ZHc foo; c 'foo\n' 'fn=1:se=2' -Hc foo; c 'foo\n' 'fn=1:se=2:ln=3' -L x; c 'foo\n' 'fn=1:se=2:ln=3' -ZL x; c 'foo\nbar\n' 'sl=1:ms=1:cx=2' -v -o -B1 bar; c 'foo\nbar\n' 'mc=4' -v -o -B1 bar; echo "-- GREP_COLOR"; printf 'foo\n' | GREP_COLOR='1;32' grep --color=always foo | show; printf 'foo\n' | GREP_COLOR='1;32' GREP_COLORS='ms=4' grep --color=always foo | show; printf 'foo\n' | GREP_COLOR='1;32' GREP_COLORS='sl=4' grep --color=always foo | show; printf 'foo\n' | GREP_COLOR='' grep --color=always foo | show; printf 'foo\n' | GREP_COLOR='1;32' grep foo
echo "== -r"; grep -r foo r | sort; echo "--"; grep -r foo r/ | sort; echo "--"; grep -r foo r/sub r/a.txt | sort; echo "--"; grep -r foo r//sub | sort; echo "-- -r file"; grep -r foo r/a.txt; grep -rH foo r/a.txt; grep -r foo r/a.txt r/a.txt; echo "-- -rh -rl -rc -rL -rn"; grep -rh foo r/sub | sort; grep -rl foo r/sub | sort; grep -rc foo r/sub | sort; grep -rL zzz r/sub | sort; grep -rn foo r/sub | sort; echo "-- -r stdin"; printf 'foo\n' | grep -r foo - r/sub/deep; echo "-- -d"; grep -d recurse foo r/sub/deep; grep -d skip foo r/sub d/x; rc; grep -d skip foo r/sub; rc; grep -d read foo r/sub; rc; grep --directories=skip foo r; rc; grep -r -d skip foo r/sub; rc; grep -d skip -r foo r/sub/deep; echo "-- -R"; grep -R foo r/sub/deep; echo "-- dot"; (cd r/sub && grep -r foo . | sort); (cd r/sub && grep -r foo | sort); (cd r/sub && grep -r foo ./ | sort); (cd r/sub && grep -r foo deep/); (cd r/sub && grep -r foo ../sub | sort); (cd r/sub && grep -rc foo | sort); echo "-- missing"; grep -r foo r/nosuch; rc; grep -r foo nosuch r/sub/deep; rc; grep -rs foo nosuch; rc; echo "-- empty dir"; mkdir r/empty; grep -r foo r/empty; rc; grep -rL foo r/empty; rc; echo "-- -r -c on a file and dir"; grep -c foo d; rc; grep -rc foo d; echo "-- -rz"; grep -rz foo r/sub/deep | show; echo "-- -r with -q"; grep -rq foo r; rc; grep -rq zzz r; rc; echo "-- -r -l -m"; grep -rl -m1 foo r/sub | sort
echo "== include exclude"; grep -r --include='*.txt' foo r | sort; echo "--"; grep -r --include='*.txt' --include='*.c' foo r | sort; echo "--"; grep -r --exclude='*.txt' foo r | sort; echo "--"; grep -r --exclude='c.txt' --exclude='b*' foo r | sort; echo "-- exclude-dir"; grep -r --exclude-dir=sub foo r | sort; echo "--"; grep -r --exclude-dir='.*' foo r | sort; echo "--"; grep -r --exclude-dir='s*' foo r | sort; echo "--"; grep -r --exclude-dir=deep foo r | sort; echo "--"; grep -r --exclude-dir=r foo r | sort; rc; grep -r --exclude-dir=sub foo r/sub | sort; grep -r --exclude-dir=sub foo r/sub/c.txt; grep -r --exclude-dir=sub foo ./r/sub; rc; grep -r --exclude-dir='*/sub' foo r | sort; grep -r --exclude-dir='sub/deep' foo r | sort; (cd r && grep -r --exclude-dir=. foo .; rc); (cd r && grep -r --exclude-dir=. foo | sort); (cd r && grep -r --exclude-dir='*' foo | sort); echo "-- include+exclude order"; grep -r --include='*.txt' --exclude='c*' foo r | sort; echo "--"; grep -r --exclude='c*' --include='*.txt' foo r | sort; echo "--"; grep -r --include=a.txt --exclude=a.txt foo r | sort; rc; grep -r --exclude=a.txt --include=a.txt foo r | sort; echo "--"; grep -r --include=a.txt --exclude='*' foo r | sort; rc; grep -r --exclude='*' --include=a.txt foo r | sort; echo "-- on command line files"; grep --include='*.c' foo r/a.txt r/b.c; rc; grep --exclude='*.c' foo r/a.txt r/b.c; rc; grep -r --exclude='a.txt' foo r/a.txt; rc; grep --exclude='r/a.txt' foo r/a.txt; rc; grep --exclude='*/a.txt' foo r/a.txt; rc; grep --exclude='r' -r foo r | sort; grep --include='x/g' foo r/a.txt; rc; grep --include='./a.txt' foo ./r/a.txt; rc; grep --include='[!a]*' foo r/a.txt r/b.c; grep --include='?.c' foo r/a.txt r/b.c; grep --include='A.TXT' foo r/a.txt; rc; grep --exclude='*' foo - < p; rc; grep --exclude='-' foo - < p; rc; grep --exclude-dir='*' foo r/a.txt; grep --exclude-dir='*' foo r/sub; rc; grep --include='sub' -r foo r | sort; rc; echo "-- exclude-from"; printf '*.txt\n*.c\n' > ex; grep -r --exclude-from=ex foo r | sort; rc; printf '*.c\r\n' > excr; grep -r --exclude-from=excr --include='*.c' --include='b*' foo r | sort; echo "-- walk uses base names"; grep -r --exclude='sub/c.txt' foo r/sub | sort; grep -r --exclude='*/c.txt' foo r/sub | sort; grep -r --include='*/c.txt' foo r/sub | sort; rc
echo "== CRLF"; printf 'foo\r\nbar\r\n' | grep 'foo$' | show; printf 'foo\r\nbar\r\n' | grep -c 'o$'; printf 'foo\r\n' | grep -x 'foo' | show; printf 'foo\r\n' | grep -xo 'foo' | show; printf 'foo\r\n' | grep -w 'foo' | show; printf 'foo\r\n' | grep -o '\S*' | show; printf 'foo\r\n' | grep -o 'foo.' | show; printf 'foo\r\n' | grep -c 'foo.$'; printf 'foo\r\n' | grep -F -x 'foo'; rc; printf 'ab\r\nfoo\r\n' | grep -b foo; printf 'ab\r\nfoo\r\n' | grep -bo oo; printf 'foo\r\n' | grep --color=always foo | show; printf 'foo\r\n' | GREP_COLORS='sl=1' grep --color=always foo | show; printf 'foo\r\n' | GREP_COLORS='sl=1' grep --color=always -v x | show; printf 'foo\r\nbar\n' | grep -c '[^a-z]$'; printf 'foo\r\n' | grep -c -U 'o$'; printf 'foo\r\n' | grep -o -U '\S*' | show; printf 'foo\r' | grep 'o' | show; printf 'a\rb\n' | grep -o 'a.b' | show; printf 'foo\r\nbar\n' | grep -o 'o*$\|bar' | show
echo "== end"

cd / && rm -rf "$dir"
