# gzip cases, run under GNU gzip 1.14 (the oracle) and under cash's builtin. The
# compressed bytes are shown only where both make the same ones: the header with
# -n and a fixed time, the trailer, and the deflate of "hello" and of nothing, which
# miniz_oxide and zlib agree on. Everything else about compression is checked by a
# round trip; what is decompressed, listed and said is checked byte for byte. Lines
# with a tab go through od. Under -r, where GNU gzip takes the file system's order
# and cash name order, the output goes through sort.
# gzip_cases.out is GNU gzip 1.14's output.
#
# Regenerate the golden file (WSL):
#   bash gzip_cases.sh > gzip_cases.out 2>&1

exec 2>&1 </dev/null
export LC_ALL=C TZ=UTC0
unset GZIP
dir=$(mktemp -d)
cd "$dir" || exit 1
show() { od -An -c | sed 's/  */ /g; s/ *$//'; }
hex() { od -An -tx1 | sed 's/  */ /g; s/ *$//'; }
rc() { echo "rc=$?"; }
# A fixed gzip member of "hello\n" with a stored name, time and the deflate both make.
member() { printf '\037\213\010\010\245\135\015\136\000\003h\000\313\110\315\311\311\347\002\000\040\060\072\066\006\000\000\000'; }
# The same without a name or a time.
bare() { printf '\037\213\010\000\000\000\000\000\000\003\313\110\315\311\311\347\002\000\040\060\072\066\006\000\000\000'; }

printf 'hello\n' > h; touch -d '2020-01-02 03:04:05' h
printf 'goodbye world\n' > g; touch -d '2020-01-02 03:04:05' g
: > e; touch -d '2020-01-02 03:04:05' e

echo "== --help"; gzip --help | head -26; rc; gunzip --help | head -1; zcat -h | head -1
echo "== bad options"; gzip -Y; rc; gzip --foo; rc; gzip --s; rc; gzip --b; rc; gzip -S; rc; gzip --suffix; rc; gzip --best=3; rc; gzip -Z h; rc; gzip --bits=x -c h; rc; gzip -S '' h; rc; gzip -S .abcdefghijklmnopqrstuvwxyz0123 h; rc
echo "== header and trailer"; gzip -c h | hex; gzip -nc h | hex; gzip -1nc h | hex; gzip -9nc h | hex; gzip --fast -nc h | hex; gzip --best -nc h | hex; gzip --rsyncable -nc h | hex; gzip -c e | hex; gzip -c < h | hex; cat h | gzip -c | hex; gzip -c - < h | hex
echo "== round trips"; head -c 20000 /dev/urandom | base64 > rnd; for l in 1 5 9; do gzip -$l -c rnd | gzip -dc | cmp - rnd && echo "level $l ok"; done; yes | head -c 300000 > y; gzip -c y | gzip -t && echo "y ok"; gzip -c y | gzip -dc | cmp - y && echo "y same"; gzip -c y e h | gzip -dc | tail -c 6
echo "== replace in place"; cp h r; touch -d '2020-01-02 03:04:05' r; gzip r; rc; ls r*; stat -c '%Y %n' r.gz; gzip -c r.gz | gzip -dc | gzip -dc; gzip -d r.gz; rc; ls r*; stat -c '%Y %n' r; cat r
echo "== -v"; cp h v; touch -d '2020-01-02 03:04:05' v; gzip -v v 2>&1 | show; gzip -dv v.gz 2>&1 | show; gzip -vc h 2>&1 >/dev/null | show; printf 'hello\n' | gzip -v 2>&1 >/dev/null | show; gzip -c h > t.gz; gzip -tv t.gz 2>&1 | show; gzip -t t.gz; rc; cat t.gz | gzip -tv 2>&1 | show; cat t.gz | gzip -dv 2>&1 | show; gzip -kv h 2>&1 | show; gzip -kvf h 2>&1 | show; gzip -dkv h.gz 2>&1 | show; gzip -dkvf h.gz 2>&1 | show; ls h*; rm h.gz; cp e ev; gzip -v ev 2>&1 | show; gzip -dv ev.gz 2>&1 | show; gzip -vq -c h 2>&1 >/dev/null | show; gzip -qv -c h 2>&1 >/dev/null | show
echo "== -k and -c"; cp h k; gzip -k k; ls k*; gzip -dk k.gz; rc; gzip -dkf k.gz; rc; ls k*; gzip -c k > kc.gz; ls k*; gzip -dc kc.gz; ls kc*
echo "== gunzip and zcat"; gzip -c h > z.gz; zcat z.gz; rc; ls z*; cp z.gz z2.gz; gunzip z2.gz; rc; ls z2*; zcat -l z.gz; gunzip -c z.gz; gunzip -t z.gz; rc; zcat h; rc; gunzip h; rc; zcat nosuch; rc; gunzip -Y; rc; gunzip -k z.gz; ls z*; gzip -cd z.gz; gzip -dc z.gz h z.gz; rc
echo "== -f and overwrite"; cp h o; gzip -c h > o.gz; gzip o; rc; gzip -q o; rc; ls o*; gzip -f o; rc; ls o*; cp h o; gzip -d o.gz; rc; gzip -df o.gz; rc; ls o*; cp h o2.gz; gzip -c h > o2; gzip -dc o2 > /dev/null; rc; gzip -d o2.gz; rc
echo "== -t on good and corrupt"; bare > good.gz; gzip -t good.gz; rc; gzip -tv good.gz 2>&1 | show; head -c 15 good.gz > trunc.gz; gzip -t trunc.gz; rc; gzip -tv trunc.gz 2>&1 | show; gzip -d trunc.gz; rc; ls trunc*; gzip -dc trunc.gz | hex; cp good.gz bad.gz; printf '\377' | dd of=bad.gz bs=1 seek=10 conv=notrunc 2>/dev/null; gzip -t bad.gz; rc; gzip -tv bad.gz 2>&1 | show; gzip -d bad.gz; rc; ls bad*; cp good.gz crc.gz; printf '\000' | dd of=crc.gz bs=1 seek=18 conv=notrunc 2>/dev/null; gzip -t crc.gz; rc; gzip -tv crc.gz 2>&1 | show; gzip -dc crc.gz | hex; cp good.gz len.gz; printf '\007' | dd of=len.gz bs=1 seek=22 conv=notrunc 2>/dev/null; gzip -t len.gz; rc; gzip -dc len.gz | hex; cp h n.gz; gzip -t n.gz; rc; gzip -d n.gz; rc; ls n*; gzip -tv n.gz 2>&1 | show; gzip -dc n.gz; rc; gzip -t good.gz n.gz good.gz; rc; gzip -tv good.gz n.gz good.gz 2>&1 | show; gzip -t good.gz bad.gz good.gz; rc; gzip -t good.gz trunc.gz good.gz; rc; gzip -t good.gz crc.gz good.gz; rc; gzip -t good.gz nosuch good.gz; rc; : > empty.gz; gzip -t empty.gz; rc; printf '\037\213\010' > hdr.gz; gzip -t hdr.gz; rc; printf 'x' | gzip -d; rc; printf '' | gzip -dc; rc; printf '\037\213\011\000\000\000\000\000\000\003' > m.gz; gzip -t m.gz; rc; printf '\037\213\010\040\000\000\000\000\000\003' > enc.gz; gzip -t enc.gz; rc; printf '\037\213\010\100\000\000\000\000\000\003' > res.gz; gzip -t res.gz; rc; printf '\037\213\010\002\000\000\000\000\000\003\000\000' > hc.gz; gzip -t hc.gz; rc; printf 'PK\003\004junk' > pk.gz; gzip -t pk.gz; rc
echo "== extra field and comment"; printf '\037\213\010\004\000\000\000\000\000\003\002\000AB\313\110\315\311\311\347\002\000\040\060\072\066\006\000\000\000' > xf.gz; gzip -t xf.gz; rc; gzip -tv xf.gz 2>&1 | show; gzip -dc xf.gz; gzip -l xf.gz; printf '\037\213\010\020\000\000\000\000\000\003a comment\000\313\110\315\311\311\347\002\000\040\060\072\066\006\000\000\000' > cm.gz; gzip -tv cm.gz 2>&1 | show; gzip -dc cm.gz
echo "== trailing"; { bare; printf 'junk'; } > tg.gz; gzip -t tg.gz; rc; gzip -tv tg.gz 2>&1 | show; gzip -dc tg.gz; rc; gzip -dq tg.gz; rc; ls tg*; { bare; printf '\000\000\000'; } > tz.gz; gzip -t tz.gz; rc; gzip -tv tz.gz 2>&1 | show; gzip -d tz.gz; rc; ls tz*; { bare; printf '\000\000x'; } > tzx.gz; gzip -t tzx.gz; rc; { bare; printf '\037'; } > t1.gz; gzip -t t1.gz; rc; { bare; printf 'j'; } > tj.gz; gzip -t tj.gz; rc; { bare; printf '\037\213'; } > t2.gz; gzip -t t2.gz; rc
echo "== -l"; member > l.gz; touch -d '2021-05-06 07:08:09' l.gz; gzip -l l.gz; rc; gzip -lv l.gz; gzip -lN l.gz; gzip -lvN l.gz; bare > ln.gz; touch -d '2021-05-06 07:08:09' ln.gz; gzip -lv ln.gz; gzip -lvN ln.gz; gzip -l l.gz ln.gz; rc; gzip -lq l.gz ln.gz; rc; gzip -lv l.gz ln.gz; gzip -l < l.gz; cat l.gz | gzip -l; cat l.gz | gzip -lv; gzip -l l.gz h; rc; gzip -l h; rc; gzip -l nosuch; rc; gzip -l l.gz nosuch; rc; gzip -l e; rc; gzip -l l.gz bad.gz ln.gz; rc; gzip -l l.gz trunc.gz; rc; gzip -c e > em.gz; touch -d "2021-05-06 07:08:09" em.gz; gzip -l em.gz; gzip -lv em.gz; mkdir nest; cp l.gz nest/deep.gz; touch -d "2021-05-06 07:08:09" nest/deep.gz; gzip -l nest/deep.gz; gzip -lN nest/deep.gz; gzip -l -S .suf l.gz; gzip -S .suf -l l.gz; gzip -ltv l.gz; rc
echo "== -l multi"; { bare; member; } > two.gz; touch -d '2021-05-06 07:08:09' two.gz; gzip -l two.gz; gzip -lv two.gz; gzip -dc two.gz; gzip -dv two.gz 2>&1 | show; ls two*; { member; bare; } > two2.gz; touch -d "2021-05-06 07:08:09" two2.gz; gzip -lv two2.gz; gzip -lN two2.gz; gzip -dN two2.gz; rc; ls two2* h; cat h
echo "== -n and -N"; gzip -nc h | gzip -lvN; gzip -Nc h | gzip -lvN; gzip -nN -c h | gzip -lvN; gzip -Nn -c h | gzip -lvN; member > nn.gz; touch -d '2021-05-06 07:08:09' nn.gz; gzip -d nn.gz; stat -c '%Y %n' nn; member > nn2.gz; touch -d '2021-05-06 07:08:09' nn2.gz; rm -f h; gzip -dN nn2.gz; rc; ls nn2* h; stat -c '%Y %n' h; member > nn3.gz; touch -d '2021-05-06 07:08:09' nn3.gz; gzip -dNv nn3.gz 2>&1 | show; rc; ls nn3* h; gzip -dNf nn3.gz; ls nn3* h; stat -c '%Y %n' h; member > nn4.gz; touch -d '2021-05-06 07:08:09' nn4.gz; gzip -dn nn4.gz; stat -c '%Y %n' nn4; bare > nn5.gz; touch -d '2021-05-06 07:08:09' nn5.gz; gzip -dN nn5.gz; stat -c '%Y %n' nn5; member > nest/x.gz; gzip -dN nest/x.gz; ls nest; cat nest/h; member | gzip -dN | hex; ls h; member | gzip -lN; printf '\037\213\010\010\000\000\000\000\000\003sub/evil\000\313\110\315\311\311\347\002\000\040\060\072\066\006\000\000\000' > ev.gz; gzip -lN ev.gz; gzip -dN ev.gz; rc; ls ev* evil; cp h ts; touch -d '2020-01-02 03:04:05' ts; gzip ts; stat -c '%Y %n' ts.gz; gzip -dN ts.gz; stat -c '%Y %n' ts; cp h old; touch -d '1960-01-01 00:00:00' old; gzip -c old | hex; rc; gzip -q -c old | hex; rc; gzip -vc old 2>&1 >/dev/null | show; cp h z0; touch -d '1970-01-01 00:00:00' z0; gzip -nc z0 | hex; rc; cp h edge; touch -d '2106-02-07 06:28:15' edge; gzip -c edge | hex; rc
echo "== -S"; cp h s; gzip -S .suf s; rc; ls s*; gzip -d s.suf; rc; gzip -S .suf -d s.suf; rc; ls s*; gzip -S suf s; ls s*; gzip -S suf -d ssuf; ls s*; gzip --suffix=.z s; ls s*; gzip --suf .z -d s.z; ls s*; gzip -S.q s; ls s*; gzip -dS.q s.q; ls s*; cp h sg.gz; gzip -S .suf sg.gz; rc; gzip -S .suf -f sg.gz; rc; ls sg*; gzip -S .suf -c h > s14.suf; gzip -l s14.suf; rc; gzip -S .suf -l s14.suf; gzip -S .suf -dc s14.suf; gzip -S /x h; rc; gzip -S .suf s; cp s.suf s2.gz; gzip -S .suf -d s2.gz; ls s2*
echo "== suffix rules"; for n in mc1.GZ mc2.Gz tt1.tgz tt2.TGZ ta.taz dash-gz under_z dz-z x.tar.gz y.gz.gz; do bare > "$n"; gzip -d "$n"; rc; done; ls; gzip -d y.gz; rc; bare > sp.Z; gzip -d sp.Z; rc; ls sp*; bare > .gz; gzip -d .gz; rc; bare > nest/.gz; gzip -d nest/.gz; rc; ls -a nest; cp h tar; gzip tar; ls tar*; gzip -d tar.gz; cp h u.txt; gzip -d u.txt; rc; gzip -dq u.txt; rc; gzip -dv u.txt; rc; gzip -l u.txt; rc; gzip -t u.txt; rc; gzip -dc u.txt; rc
echo "== already has suffix"; cp h a.gz; gzip a.gz; rc; gzip -q a.gz; rc; gzip -v a.gz; rc; gzip -S .suf a.gz; rc; cp h b.GZ; gzip b.GZ; rc; cp h a.tgz; gzip a.tgz; rc; gzip -f b.GZ; rc; ls a* b*; gzip -c a.gz | gzip -dc | cmp - h && echo "compressed twice"
echo "== missing and directory"; gzip nosuch; rc; gzip -q nosuch; rc; gzip -d nosuch; rc; gzip -d nosuch.gz; rc; gzip -c nosuch; rc; gzip -v nosuch 2>&1 | show; gzip nosuch h; rc; ls h*; gzip -d h.gz; mkdir d; gzip d; rc; gzip -q d; rc; gzip -d d; rc; gzip -c d; rc; gzip -l d; rc; gzip -v d 2>&1 | show; gzip d h; rc; ls h*; gzip -d h.gz
echo "== gunzip finds the suffix"; gzip -c h > find.gz; gunzip find; rc; ls find*; gzip -S .suf -c h > find2.suf; gunzip -S .suf find2; rc; ls find2*; gzip -c h > find3.tgz; gunzip find3; rc; ls find3*
echo "== hard links"; cp h l1; ln l1 l2; gzip l1; rc; ln l1 l3; gzip l1; rc; gzip -q l1; rc; gzip -c l1 | gzip -dc; gzip -k l1; rc; gzip -f l1; rc; ls l1* l2 l3; cp l1.gz lg.gz; ln lg.gz lg2.gz; gzip -d lg.gz; rc; gzip -dc lg.gz; gzip -df lg.gz; rc; ls lg*
echo "== -r"; mkdir -p tree/sub; printf 'a\n' > tree/a; printf 'b\n' > tree/sub/b; gzip -c h > tree/c.gz; cp h tree/d.txt; gzip -r tree; rc; find tree | sort; gzip -dr tree; rc; find tree | sort; gzip -rv tree 2>&1 | sort; rc; gzip -drv tree 2>&1 | sort; gzip -r tree; gzip -rl tree | sort; rc; gzip -rt tree; rc; gzip -rtv tree 2>&1 | sort; gzip -dr tree; gzip -r tree/a tree/sub; find tree | sort; gzip -dr tree; gzip -r nosuch; rc; gzip -rc tree | gzip -dc | sort; gzip -rk tree; find tree | sort; { gzip -r tree; rc; } 2>&1 | sort; gzip -rv tree 2>&1 | sort; rc; gzip -rd tree 2>&1 | sort; { gzip -rd tree; rc; } 2>&1 | sort; gzip -rdv tree 2>&1 | sort; rc; gzip -rtv tree 2>&1 | sort; rc; gzip -rl tree 2>&1 | sort; rc; rm -f tree/*.gz tree/sub/*.gz; gzip -r -S .suf tree; find tree | sort; gzip -rd -S .suf tree; find tree | sort; zcat -r tree 2>&1 | sort
echo "== stdin and dash"; printf 'hi\n' | gzip | gzip -dc; printf 'hi\n' | gzip - | gzip -dc; printf 'hi\n' | gzip -c - h | gzip -dc; printf 'hi\n' | gzip -v - 2>&1 >/dev/null | show; printf 'hi\n' | gzip -dv -; rc; printf 'hi\n' | gzip -- - | gzip -dc; gzip -c h - < g | gzip -dc; printf 'hello\n' | gzip -dfc; rc; gzip -dfc h; rc; printf '\037' | gzip -dfc | hex; printf '' | gzip -dfc; rc; cp h pt; gzip -df pt; rc; ls pt*; printf '' | gzip -c | hex; printf '' | gzip -cv 2>&1 | show
echo "== -q and warnings"; gzip -q nosuch; rc; cp h n.gz; gzip -dq n.gz; rc; gzip -dcq tg.gz > /dev/null; rc
echo "== GZIP environment"; GZIP=-9 gzip -nc h | hex; rc; GZIP=-1 gzip -nc h | hex; GZIP=-9 gzip -1nc h | hex; GZIP='-n -v' gzip -c h 2>&1 >/dev/null | hex; rc; GZIP=-c gzip -nc h | hex; rc; GZIP=-d gzip -nc h | hex; rc; GZIP=foo gzip -nc h | hex; rc; GZIP='-9 -- -1' gzip -nc h | hex; GZIP=--best gzip -nc h | hex
echo "== --ascii and -b"; gzip -a -nc h | hex; rc; gzip --ascii -nc h | hex; rc; gzip -b 9 -nc h | hex; rc; gzip --bits 9 -nc h | hex; rc
echo "== --version"; gzip -V | head -1; gzip --version | head -1; gunzip --version | head -1; zcat --version | head -1
echo "== -c to a file already there"; gzip -c h > cc.gz; gzip -c h > cc.gz; rc; gzip -l cc.gz; gzip -dc cc.gz
echo "== read-only input"; cp h ro; chmod 444 ro; gzip ro; rc; [ -w ro.gz ] && echo writable || echo read-only; gzip -d ro.gz; rc; [ -w ro ] && echo writable || echo read-only; ls ro*

cd / && rm -rf "$dir"
