//! Optional bundled coreutils for cash, powered by uutils/coreutils.
//!
//! Each utility is feature-gated (e.g., `coreutils.cat`, `coreutils.ls`) and
//! can be individually enabled or disabled. The `coreutils.all` feature enables
//! all cross-platform utilities.
//!
//! The crate exposes [`bundled_commands`], a registry of utility name to
//! `uumain`-style function pointer. The binary consumer (typically
//! brush-shell) installs this registry at startup; when its bundled-dispatch
//! protocol fires, the registered function is called directly. The consumer
//! is also responsible for registering any per-name builtin shims that
//! re-enter the binary as an external process, so shell redirections, pipes,
//! and process-group state are honored by uutils transparently.
//!
//! ## Relationship to `uucore::bin!`
//!
//! Each adapter generated by `register!` is a hand-rolled port of the body
//! of upstream's `uucore::bin!($util)` macro (SIGPIPE setup, Fluent
//! localization, `uumain` call, stdout flush). We can't invoke the macro
//! directly because it expands to a `pub fn main()` that reads argv via
//! `uucore::args_os()` and terminates the process with `std::process::exit`.
//! Our call shape is different: adapters receive argv as a parameter (the
//! `--invoke-bundled` dispatcher owns argv slicing) and must *return* an exit
//! code so the dispatcher can run a single `exit` site.
//!
//! Intentional divergences from `bin!`, all of which are benign in our usage:
//!
//! * **No `exit`:** adapters return `i32` instead of calling
//!   `std::process::exit`.
//! * **Caller-supplied argv:** `args` is passed in rather than pulled from
//!   `uucore::args_os()`.
//! * **Simpler `LocalizationError` formatting:** we render with `Display`
//!   rather than matching on `ParseResource` for snippet-aware output.

use std::collections::HashMap;
use std::ffi::OsString;

// cash: the tools taken from uutils and made cash's own, under the names their
// adapters give uucore for its own messages.
#[cfg(feature = "coreutils.rm")]
use cash_uutils::rm as uu_rm;
#[cfg(feature = "coreutils.shuf")]
use cash_uutils::shuf as uu_shuf;
#[cfg(feature = "coreutils.sort")]
use cash_uutils::sort as uu_sort;
#[cfg(feature = "coreutils.tee")]
use cash_uutils::tee as uu_tee;
#[cfg(feature = "coreutils.uniq")]
use cash_uutils::uniq as uu_uniq;

/// First half of the `uucore::bin!` body: install SIGPIPE handling and
/// initialize the thread-local Fluent localizer. Without this, `translate!`
/// calls inside the utility fall back to emitting raw Fluent keys (e.g.,
/// `ls-error-cannot-access-no-such-file`) instead of rendered messages.
///
/// `util_crate_name` is the upstream crate name (e.g., `"uu_dir"`), matching
/// what `bin!` passes via `stringify!($util)`. We route it through
/// [`uucore::get_canonical_util_name`] to apply upstream's alias map (`dir` →
/// `ls`, `vdir` → `ls`, `[` → `test`); utilities implemented as thin wrappers
/// over another crate load their translation bundle under the wrapped name,
/// so skipping this step silently breaks localization for the aliases.
///
/// Matches `uucore::bin!` behavior on localization-init failure: exit 99.
/// (This is uutils' contract, not brush's — the fact that brush-core uses 99
/// for `ExecutionExitCode::Unimplemented` is coincidental.)
/// `setup_localization` is idempotent per thread, so repeated invocations
/// (e.g., successive bundled-dispatch calls in a long-lived host, if that
/// ever happens) are cheap.
#[allow(
    dead_code,
    reason = "only called by adapters generated by the `register!` macro; with no coreutils.* features enabled, no adapter exists"
)]
fn prepare_uutil_runtime(util_crate_name: &str) {
    uucore::panic::preserve_inherited_sigpipe();
    uucore::panic::mute_sigpipe_panic();
    let localization_name = uucore::get_canonical_util_name(util_crate_name);
    if let Err(err) = uucore::locale::setup_localization(localization_name) {
        eprintln!("cash: could not initialize localization for '{localization_name}': {err}");
        std::process::exit(99);
    }
}

/// Second half of the `uucore::bin!` body: flush stdout after `uumain`
/// returns. `bin!` does this before calling `std::process::exit` to work
/// around <https://github.com/rust-lang/rust/issues/23818>. We do it here so
/// callers that don't immediately `exit` (e.g., a test harness) still observe
/// complete output.
#[allow(
    dead_code,
    reason = "only called by adapters generated by the `register!` macro; with no coreutils.* features enabled, no adapter exists"
)]
fn finalize_uutil_runtime() {
    use std::io::Write;
    if let Err(e) = std::io::stdout().flush() {
        eprintln!("cash: error flushing stdout: {e}");
    }
}

/// Adapts a uutils `uumain` (`impl Iterator<Item = OsString> -> i32`) to a
/// plain `fn(Vec<OsString>) -> i32` and inserts it into the registry under
/// the given name when its feature is enabled. The generated adapter mirrors
/// the body of `uucore::bin!`; see the module-level docs for why we port it
/// by hand rather than invoke the macro.
macro_rules! register {
    ($map:expr, $feature:literal, $name:literal, $util_crate:ident) => {
        #[cfg(feature = $feature)]
        {
            fn adapter<I>(args: I) -> i32
            where
                I: IntoIterator<Item = OsString>,
            {
                $crate::prepare_uutil_runtime(stringify!($util_crate));
                let code = $util_crate::uumain(args.into_iter());
                $crate::finalize_uutil_runtime();
                code
            }
            $map.insert($name.to_string(), adapter as fn(Vec<OsString>) -> i32);
        }
    };
}

/// Returns the set of bundled coreutils commands enabled by feature flags.
///
/// Keyed by utility name (e.g., `"cat"`); values are `uumain`-shaped entry
/// points that consume a full argv (with `argv[0]` as the command name) and
/// return an exit code.
#[allow(clippy::too_many_lines)]
#[must_use]
pub fn bundled_commands() -> HashMap<String, fn(Vec<OsString>) -> i32> {
    #[allow(
        unused_mut,
        reason = "every register! is cfg'd on a coreutils.* feature; with none enabled, nothing mutates the map"
    )]
    let mut m = HashMap::<String, fn(Vec<OsString>) -> i32>::new();

    register!(m, "coreutils.arch", "arch", uu_arch);
    register!(m, "coreutils.base32", "base32", uu_base32);
    register!(m, "coreutils.base64", "base64", uu_base64);
    register!(m, "coreutils.basename", "basename", uu_basename);
    register!(m, "coreutils.basenc", "basenc", uu_basenc);
    register!(m, "coreutils.cat", "cat", uu_cat);
    register!(m, "coreutils.cksum", "cksum", uu_cksum);
    register!(m, "coreutils.b2sum", "b2sum", uu_b2sum);
    register!(m, "coreutils.md5sum", "md5sum", uu_md5sum);
    register!(m, "coreutils.sha1sum", "sha1sum", uu_sha1sum);
    register!(m, "coreutils.sha224sum", "sha224sum", uu_sha224sum);
    register!(m, "coreutils.sha256sum", "sha256sum", uu_sha256sum);
    register!(m, "coreutils.sha384sum", "sha384sum", uu_sha384sum);
    register!(m, "coreutils.sha512sum", "sha512sum", uu_sha512sum);
    register!(m, "coreutils.comm", "comm", uu_comm);
    register!(m, "coreutils.cp", "cp", uu_cp);
    register!(m, "coreutils.csplit", "csplit", uu_csplit);
    register!(m, "coreutils.cut", "cut", uu_cut);
    register!(m, "coreutils.date", "date", uu_date);
    register!(m, "coreutils.dd", "dd", uu_dd);
    register!(m, "coreutils.df", "df", uu_df);
    register!(m, "coreutils.dir", "dir", uu_dir);
    register!(m, "coreutils.dircolors", "dircolors", uu_dircolors);
    register!(m, "coreutils.dirname", "dirname", uu_dirname);
    register!(m, "coreutils.du", "du", uu_du);
    register!(m, "coreutils.echo", "echo", uu_echo);
    register!(m, "coreutils.env", "env", uu_env);
    register!(m, "coreutils.expand", "expand", uu_expand);
    register!(m, "coreutils.expr", "expr", uu_expr);
    register!(m, "coreutils.factor", "factor", uu_factor);
    register!(m, "coreutils.false", "false", uu_false);
    register!(m, "coreutils.fmt", "fmt", uu_fmt);
    register!(m, "coreutils.fold", "fold", uu_fold);
    register!(m, "coreutils.head", "head", uu_head);
    register!(m, "coreutils.hostname", "hostname", uu_hostname);
    register!(m, "coreutils.join", "join", uu_join);
    register!(m, "coreutils.link", "link", uu_link);
    register!(m, "coreutils.ln", "ln", uu_ln);
    register!(m, "coreutils.ls", "ls", uu_ls);
    register!(m, "coreutils.mkdir", "mkdir", uu_mkdir);
    register!(m, "coreutils.mktemp", "mktemp", uu_mktemp);
    register!(m, "coreutils.more", "more", uu_more);
    register!(m, "coreutils.mv", "mv", uu_mv);
    register!(m, "coreutils.nl", "nl", uu_nl);
    register!(m, "coreutils.nproc", "nproc", uu_nproc);
    register!(m, "coreutils.numfmt", "numfmt", uu_numfmt);
    register!(m, "coreutils.od", "od", uu_od);
    register!(m, "coreutils.paste", "paste", uu_paste);
    register!(m, "coreutils.pathchk", "pathchk", uu_pathchk);
    register!(m, "coreutils.pr", "pr", uu_pr);
    register!(m, "coreutils.printenv", "printenv", uu_printenv);
    register!(m, "coreutils.printf", "printf", uu_printf);
    register!(m, "coreutils.ptx", "ptx", uu_ptx);
    register!(m, "coreutils.pwd", "pwd", uu_pwd);
    register!(m, "coreutils.readlink", "readlink", uu_readlink);
    register!(m, "coreutils.realpath", "realpath", uu_realpath);
    register!(m, "coreutils.rm", "rm", uu_rm);
    register!(m, "coreutils.rmdir", "rmdir", uu_rmdir);
    register!(m, "coreutils.seq", "seq", uu_seq);
    register!(m, "coreutils.shred", "shred", uu_shred);
    register!(m, "coreutils.shuf", "shuf", uu_shuf);
    register!(m, "coreutils.sleep", "sleep", uu_sleep);
    register!(m, "coreutils.sort", "sort", uu_sort);
    register!(m, "coreutils.split", "split", uu_split);
    register!(m, "coreutils.sum", "sum", uu_sum);
    register!(m, "coreutils.sync", "sync", uu_sync);
    register!(m, "coreutils.tac", "tac", uu_tac);
    register!(m, "coreutils.tail", "tail", uu_tail);
    register!(m, "coreutils.tee", "tee", uu_tee);
    // cash: §2 notes MS Coreutils withholds `timeout` over a shell-name conflict.
    // cash owns name resolution, so that conflict does not apply here.
    register!(m, "coreutils.timeout", "timeout", uu_timeout);
    register!(m, "coreutils.uptime", "uptime", uu_uptime);
    register!(m, "coreutils.test", "test", uu_test);
    register!(m, "coreutils.touch", "touch", uu_touch);
    register!(m, "coreutils.tr", "tr", uu_tr);
    register!(m, "coreutils.true", "true", uu_true);
    register!(m, "coreutils.truncate", "truncate", uu_truncate);
    register!(m, "coreutils.tsort", "tsort", uu_tsort);
    register!(m, "coreutils.uname", "uname", uu_uname);
    register!(m, "coreutils.unexpand", "unexpand", uu_unexpand);
    register!(m, "coreutils.uniq", "uniq", uu_uniq);
    register!(m, "coreutils.unlink", "unlink", uu_unlink);
    register!(m, "coreutils.vdir", "vdir", uu_vdir);
    register!(m, "coreutils.wc", "wc", uu_wc);
    register!(m, "coreutils.whoami", "whoami", uu_whoami);
    register!(m, "coreutils.yes", "yes", uu_yes);

    // cash: the listing commands colour by default when they are writing to a terminal.
    #[cfg(feature = "coreutils.ls")]
    m.insert("ls".to_string(), colouring_ls as fn(Vec<OsString>) -> i32);
    #[cfg(feature = "coreutils.dir")]
    m.insert("dir".to_string(), colouring_dir as fn(Vec<OsString>) -> i32);
    #[cfg(feature = "coreutils.vdir")]
    m.insert(
        "vdir".to_string(),
        colouring_vdir as fn(Vec<OsString>) -> i32,
    );

    m
}

/// Where the command sits in the argv of a bundled utility that runs one.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct CommandOperand {
    /// The argv, rewritten only as far as needed to find the command: `env -S` strings
    /// are split into the words `env` would have made of them.
    pub args: Vec<OsString>,
    /// Index into `args` of the command's name; its arguments follow it.
    pub index: usize,
    /// The directory the utility will run the command in (`env -C`), if not its own.
    pub chdir: Option<OsString>,
    /// The PATH the utility will search, if it sets one (`env PATH=…`, `env -i`).
    pub path: Option<OsString>,
}

/// cash: finds the command a bundled `env` or `timeout` would run, so the dispatcher can
/// run it through cash instead when it needs arguments encoded for MSYS2 (D52).
///
/// `args[0]` names the utility. `None` means it runs no command, or its arguments do not
/// parse, and the utility should simply be left to report that itself.
#[must_use]
pub fn command_operand(args: &[OsString]) -> Option<CommandOperand> {
    #[cfg(feature = "coreutils.env")]
    if args.first().is_some_and(|name| name == "env") {
        return env_operand(args);
    }
    #[cfg(feature = "coreutils.timeout")]
    if args.first().is_some_and(|name| name == "timeout") {
        prepare_uutil_runtime(stringify!(uu_timeout));
        // `command` takes the rest of the command line, so it is the tail of `args`.
        let matches = uu_timeout::uu_app().try_get_matches_from(args).ok()?;
        return Some(CommandOperand {
            args: args.to_vec(),
            index: args
                .len()
                .checked_sub(matches.get_many::<String>("command")?.len())?,
            chdir: None,
            path: None,
        });
    }
    let _ = args;
    None
}

/// [`command_operand`] for `env`, which parses as uutils' `env` does: `-S` strings are
/// split first, then clap reads the options, then every `NAME=VALUE` (and `-`) is an
/// assignment up to the first word that is not.
#[cfg(feature = "coreutils.env")]
fn env_operand(args: &[OsString]) -> Option<CommandOperand> {
    prepare_uutil_runtime(stringify!(uu_env));
    let args = split_env_strings(args)?;
    let matches = uu_env::uu_app().try_get_matches_from(&args).ok()?;
    let mut path = matches.get_flag("ignore-environment").then(OsString::new);
    let unsets_path = matches
        .get_many::<OsString>("unset")
        .is_some_and(|mut names| names.any(|name| name.eq_ignore_ascii_case("PATH")));
    if unsets_path {
        path = Some(OsString::new());
    }
    let chdir = matches.get_one::<OsString>("chdir").cloned();

    // `vars` takes the rest of the command line once it starts, so its values are the
    // tail of `args`. (clap's own indices count `-o=val` and `-abc` as several words.)
    let values = matches.get_many::<OsString>("vars")?;
    let first = args.len().checked_sub(values.len())?;
    for (value, index) in values.zip(first..) {
        if value == "-" {
            path.get_or_insert_with(OsString::new);
            continue;
        }
        let text = value.to_string_lossy();
        let Some((name, rest)) = text.split_once('=') else {
            return Some(CommandOperand {
                args,
                index,
                chdir,
                path,
            });
        };
        if name.eq_ignore_ascii_case("PATH") {
            path = Some(OsString::from(rest));
        }
    }
    None
}

/// `args` with each `env -S STRING` (in the spellings uutils accepts) replaced by the
/// words it splits into, which is what uutils' `env` hands clap.
#[cfg(feature = "coreutils.env")]
fn split_env_strings(args: &[OsString]) -> Option<Vec<OsString>> {
    use uu_env::native_int_str::{
        from_native_int_representation_owned, to_native_int_representation,
    };

    let split = |text: &std::ffi::OsStr| -> Option<Vec<OsString>> {
        let words = uu_env::parse_args_from_str(&to_native_int_representation(text)).ok()?;
        Some(
            words
                .into_iter()
                .map(from_native_int_representation_owned)
                .collect(),
        )
    };

    let mut out = Vec::with_capacity(args.len());
    let mut rest = args.iter().enumerate();
    let mut expecting_value = false;
    while let Some((n, arg)) = rest.next() {
        let text = arg.to_string_lossy();
        // Options end at `--` or the first word that is neither an option nor an
        // assignment, and after that nothing is split.
        if n > 0
            && !expecting_value
            && (text == "--" || !(text.starts_with('-') || text.contains('=')))
        {
            out.extend(args.iter().skip(n).cloned());
            return Some(out);
        }
        expecting_value = false;
        if let Some(joined) = ["--split-string", "-S", "-vS", "-vvS"]
            .iter()
            .find_map(|flag| {
                text.strip_prefix(flag)
                    .filter(|s| !s.is_empty())
                    .map(|s| (flag, s))
            })
        {
            let (flag, value) = joined;
            if flag.starts_with("-v") {
                out.push(OsString::from(if *flag == "-vS" { "-v" } else { "-vv" }));
            }
            let value = if *flag == "--split-string" {
                value.strip_prefix('=').unwrap_or(value)
            } else {
                value
            };
            out.extend(split(std::ffi::OsStr::new(value))?);
        } else if ["--split-string", "-S", "-vS", "-vvS"].contains(&&*text) {
            let Some((_, value)) = rest.next() else {
                out.push(arg.clone());
                continue;
            };
            if text.starts_with("-v") {
                out.push(OsString::from(if text == "-vS" { "-v" } else { "-vv" }));
            }
            out.extend(split(value)?);
        } else {
            if let Some(long) = text.strip_prefix("--") {
                expecting_value = ["argv0", "chdir", "file", "unset"].contains(&long);
            } else if let Some(short) = text.strip_prefix('-') {
                expecting_value = short.chars().last().is_some_and(|c| "aCfu".contains(c));
            }
            out.push(arg.clone());
        }
    }
    Some(out)
}

/// Whether the caller already said something about colour, in any of its spellings.
///
/// `--color`, `--colour`, `--color=never` and `-N`-style bundles all count: if the
/// command line mentions it, cash has no business having an opinion.
#[cfg(any(
    feature = "coreutils.ls",
    feature = "coreutils.dir",
    feature = "coreutils.vdir"
))]
fn colour_already_decided(args: &[OsString]) -> bool {
    args.iter().any(|arg| {
        let arg = arg.to_string_lossy();
        arg.starts_with("--color") || arg.starts_with("--colour")
    })
}

/// cash: ask for colour when nothing else has.
///
/// Every Linux distribution ships `alias ls='ls --color=auto'` in `/etc/bash.bashrc` or
/// the like, which is why `ls` looks coloured on Linux and looks plain here: GNU's `ls`
/// does not colour by default either, and Windows has no system rc file to carry the
/// alias. Adding one to `~/.cashrc` works, but it has to be done again on every machine,
/// and — because `ls` is a builtin (D48) — an alias is also the one spelling that has no
/// path behind it for a script that wants one.
///
/// `auto` is what makes this safe: uutils checks whether *its* stdout is a terminal, so a
/// pipe or a redirection is still plain text and nothing that parses `ls` changes
/// (§4 #24). An explicit `--color=never` still wins, because the caller said so.
#[cfg(any(
    feature = "coreutils.ls",
    feature = "coreutils.dir",
    feature = "coreutils.vdir"
))]
fn with_colour_auto(mut args: Vec<OsString>) -> Vec<OsString> {
    if colour_already_decided(&args) {
        return args;
    }

    // After argv[0], so it is an option rather than an operand, and ahead of any `--`.
    let at = usize::from(!args.is_empty());
    args.insert(at, OsString::from("--color=auto"));
    args
}

#[cfg(feature = "coreutils.ls")]
fn colouring_ls(args: Vec<OsString>) -> i32 {
    prepare_uutil_runtime(stringify!(uu_ls));
    let code = uu_ls::uumain(with_colour_auto(args).into_iter());
    finalize_uutil_runtime();
    code
}

#[cfg(feature = "coreutils.dir")]
fn colouring_dir(args: Vec<OsString>) -> i32 {
    prepare_uutil_runtime(stringify!(uu_dir));
    let code = uu_dir::uumain(with_colour_auto(args).into_iter());
    finalize_uutil_runtime();
    code
}

#[cfg(feature = "coreutils.vdir")]
fn colouring_vdir(args: Vec<OsString>) -> i32 {
    prepare_uutil_runtime(stringify!(uu_vdir));
    let code = uu_vdir::uumain(with_colour_auto(args).into_iter());
    finalize_uutil_runtime();
    code
}

#[cfg(test)]
#[cfg(all(feature = "coreutils.env", feature = "coreutils.timeout"))]
mod tests {
    use super::*;

    fn operand(args: &[&str]) -> Option<CommandOperand> {
        let args: Vec<OsString> = args.iter().map(OsString::from).collect();
        command_operand(&args)
    }

    fn strings(args: &[OsString]) -> Vec<String> {
        args.iter()
            .map(|a| a.to_string_lossy().into_owned())
            .collect()
    }

    #[test]
    fn timeout_command_follows_its_options_however_they_are_spelled() {
        assert_eq!(operand(&["timeout", "5", "prog", "-x"]).unwrap().index, 2);
        assert_eq!(
            operand(&["timeout", "-vs", "KILL", "5", "prog"])
                .unwrap()
                .index,
            4
        );
        assert_eq!(
            operand(&["timeout", "-sKILL", "-k=1", "5", "prog", "a"])
                .unwrap()
                .index,
            4
        );
        assert_eq!(operand(&["timeout", "5", "--", "prog"]).unwrap().index, 3);
        assert!(operand(&["timeout", "5"]).is_none());
    }

    #[test]
    fn env_command_follows_options_and_assignments() {
        let op = operand(&["env", "-iu", "X", "A=1", "prog", "-x"]).unwrap();
        assert_eq!((op.index, op.path), (4, Some(OsString::new())));
        let op = operand(&["env", "--chdir=/tmp", "Path=C:/bin", "prog"]).unwrap();
        assert_eq!(op.index, 3);
        assert_eq!(op.chdir, Some(OsString::from("/tmp")));
        assert_eq!(op.path, Some(OsString::from("C:/bin")));
        assert_eq!(operand(&["env", "-", "prog"]).unwrap().index, 2);
        assert!(operand(&["env", "A=1"]).is_none());
        assert!(operand(&["env"]).is_none());
    }

    #[test]
    fn env_split_strings_become_words() {
        let op = operand(&["env", "-S", "A=1 prog 'x y'", "z"]).unwrap();
        assert_eq!(strings(&op.args), ["env", "A=1", "prog", "x y", "z"]);
        assert_eq!(op.index, 2);
        let op = operand(&["env", "-vSprog x", "y"]).unwrap();
        assert_eq!(strings(&op.args), ["env", "-v", "prog", "x", "y"]);
        assert_eq!(op.index, 2);
        let op = operand(&["env", "prog", "-S", "x"]).unwrap();
        assert_eq!(strings(&op.args), ["env", "prog", "-S", "x"]);
    }
}
